### PR TITLE
Adding Animations and Node.js Server for the To-Do List

### PR DESCRIPTION
**Pull request by Rabianzo**
This pull request includes updates for the To-Do List project, adding animations to the add and delete buttons, which now reflect the primary colors (black, white, and green). It also introduces a basic Node.js server using Express to serve the HTML, CSS, and JavaScript files, improving project structure and deployment readiness.

### CODE REVIEW

**Review by LawSibisi — COMMENTED** [review]
Hi @Rabianzo , to see the changes, should we clone your repo or can please host it so we can just click to review changes you make

**Comment by Rabianzo** [comment]
> Hi @Rabianzo , to see the changes, should we clone your repo or can please host it so we can just click to review changes you make

You need to clone it to your local machine because I have not yet merged the changes into the main branch

**Review by LundiLanga — CHANGES_REQUESTED** [review]
You've done a good job so far. 

I think you should make the Done button remain green even after clicking done so that if you want to undo you can still click and make the input box sticky so when you scroll down it doesn't hide.

**Comment by sidon59** [comment]
> You've done a good job so far.
> 
> I think you should make the Done button remain green even after clicking done so that if you want to undo you can still click and make the input box sticky so when you scroll down it doesn't hide.

i agree with this

**Review by sidon59 — APPROVED** [review]

**Comment by sidon59** [comment]
i think you are good to merge now.

**Review by sidon59 — APPROVED** [review]

**Review by LundiLanga — APPROVED** [review]

**Comment by sidon59** [comment]
@Rabianzo were you able to merge?

**Comment by Rabianzo** [comment]
> @Rabianzo were you able to merge?

Not yet, we will all merge our pull requests on Thursday after we've checked everyone's work.

**Comment by Rabianzo** [comment]
> You've done a good job so far.
> 
> I think you should make the Done button remain green even after clicking done so that if you want to undo you can still click and make the input box sticky so when you scroll down it doesn't hide.

The changes have been made.

**Comment by Rabianzo** [comment]
> Hi @Rabianzo , to see the changes, should we clone your repo or can please host it so we can just click to review changes you make

You can also zip download the Development branch and run it on your local machine.

**Review by LundiLanga — APPROVED** [review]

**Review by LawSibisi — APPROVED** [review]
I have went through your project. looks good on my side.

**Pull request merged**
